server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        # Routes for user-service
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**

        # Routes for vehicle-service
        - id: vehicle-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/vehicles/**

        # Routes for parking-space-service
        - id: parking-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/parking-service/**

        # Routes for payment-service
        - id: payment-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/payments/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/